language: perl

perl:
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

install:
    - "cpanm Dist::Zilla"
    - "cpanm Moose"
    - "cpanm Test::More"

script: dzil test
